name: Say Hello

on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo message
        run: |
          echo "Hola Luis"
      - name: Tell me de date
        run: |
          date
      - run: ls -l
